// Generated by scripts/generate-contracts.mjs; do not edit.

export const browserAbis = {
  "factory": [
    {
      "type": "function",
      "name": "curveImplementation",
      "inputs": [
        {
          "name": "engineVersion",
          "type": "uint16",
          "internalType": "uint16"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "engineEnabled",
      "inputs": [
        {
          "name": "engineVersion",
          "type": "uint16",
          "internalType": "uint16"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "futureDefaults",
      "inputs": [],
      "outputs": [
        {
          "name": "defaults",
          "type": "tuple",
          "internalType": "struct LaunchTypes.FactoryDefaults",
          "components": [
            {
              "name": "parameters",
              "type": "tuple",
              "internalType": "struct LaunchTypes.CurveParameters",
              "components": [
                {
                  "name": "totalSupply",
                  "type": "uint256",
                  "internalType": "uint256"
                },
                {
                  "name": "curveTokens",
                  "type": "uint256",
                  "internalType": "uint256"
                },
                {
                  "name": "lpTokens",
                  "type": "uint256",
                  "internalType": "uint256"
                },
                {
                  "name": "graduationEth",
                  "type": "uint256",
                  "internalType": "uint256"
                },
                {
                  "name": "initialVirtualEth",
                  "type": "uint256",
                  "internalType": "uint256"
                },
                {
                  "name": "initialVirtualToken",
                  "type": "uint256",
                  "internalType": "uint256"
                },
                {
                  "name": "tradeFeeBps",
                  "type": "uint16",
                  "internalType": "uint16"
                },
                {
                  "name": "protocolShareBps",
                  "type": "uint16",
                  "internalType": "uint16"
                }
              ]
            },
            {
              "name": "weth",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "uniswapFactory",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "launchFee",
              "type": "uint256",
              "internalType": "uint256"
            }
          ]
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "launch",
      "inputs": [
        {
          "name": "request",
          "type": "tuple",
          "internalType": "struct LaunchTypes.LaunchRequest",
          "components": [
            {
              "name": "name",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "symbol",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "engineVersion",
              "type": "uint16",
              "internalType": "uint16"
            },
            {
              "name": "developerBuyGross",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "minDeveloperTokensOut",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "deadline",
              "type": "uint256",
              "internalType": "uint256"
            }
          ]
        }
      ],
      "outputs": [
        {
          "name": "token",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "curve",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "lpPair",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "payable"
    },
    {
      "type": "function",
      "name": "launchFee",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "launchesPaused",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "tradingPaused",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "event",
      "name": "TokenLaunched",
      "inputs": [
        {
          "name": "token",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "curve",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "creator",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "lpPair",
          "type": "address",
          "indexed": false,
          "internalType": "address"
        },
        {
          "name": "weth",
          "type": "address",
          "indexed": false,
          "internalType": "address"
        },
        {
          "name": "protocolTreasury",
          "type": "address",
          "indexed": false,
          "internalType": "address"
        },
        {
          "name": "engineVersion",
          "type": "uint16",
          "indexed": false,
          "internalType": "uint16"
        },
        {
          "name": "name",
          "type": "string",
          "indexed": false,
          "internalType": "string"
        },
        {
          "name": "symbol",
          "type": "string",
          "indexed": false,
          "internalType": "string"
        },
        {
          "name": "totalSupply",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "virtualEth",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "virtualToken",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "curveTokens",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "lpTokens",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "graduationEth",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "launchFeePaid",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "tradeFeeBps",
          "type": "uint16",
          "indexed": false,
          "internalType": "uint16"
        },
        {
          "name": "protocolShareBps",
          "type": "uint16",
          "indexed": false,
          "internalType": "uint16"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "AccountingInvariantFailed",
      "inputs": [
        {
          "name": "balance",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "requiredBalance",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "AlreadyGraduated",
      "inputs": []
    },
    {
      "type": "error",
      "name": "AlreadyInitialized",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ArithmeticOverflow",
      "inputs": []
    },
    {
      "type": "error",
      "name": "CurveInvariantFailed",
      "inputs": [
        {
          "name": "virtualEth",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "virtualToken",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "invariant",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "DeadlineExpired",
      "inputs": [
        {
          "name": "deadline",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "currentTimestamp",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "DeveloperBuyCapExceeded",
      "inputs": [
        {
          "name": "tokensOut",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "maximumTokensOut",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "DivisionByZero",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EngineDisabled",
      "inputs": [
        {
          "name": "engineVersion",
          "type": "uint16",
          "internalType": "uint16"
        }
      ]
    },
    {
      "type": "error",
      "name": "EngineVersionMismatch",
      "inputs": [
        {
          "name": "expected",
          "type": "uint16",
          "internalType": "uint16"
        },
        {
          "name": "actual",
          "type": "uint16",
          "internalType": "uint16"
        }
      ]
    },
    {
      "type": "error",
      "name": "EthTransferFailed",
      "inputs": [
        {
          "name": "recipient",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "FailedDeployment",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ImplementationInitializationDisabled",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InsufficientBalance",
      "inputs": [
        {
          "name": "balance",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "needed",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "InvalidAuthority",
      "inputs": [
        {
          "name": "field",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "authority",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "InvalidCurveAllocation",
      "inputs": [
        {
          "name": "curveTokens",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "lpTokens",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "InvalidCurveBoundary",
      "inputs": [
        {
          "name": "invariant",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "finalVirtualToken",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "finalVirtualEth",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "InvalidEngineImplementation",
      "inputs": [
        {
          "name": "implementation",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "InvalidGraduationEth",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidProtocolShareBps",
      "inputs": [
        {
          "name": "protocolShareBps",
          "type": "uint16",
          "internalType": "uint16"
        }
      ]
    },
    {
      "type": "error",
      "name": "InvalidRecipient",
      "inputs": [
        {
          "name": "field",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "recipient",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "InvalidSupplyAllocation",
      "inputs": [
        {
          "name": "totalSupply",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "curveTokens",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "lpTokens",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "InvalidTradeFeeBps",
      "inputs": [
        {
          "name": "tradeFeeBps",
          "type": "uint16",
          "internalType": "uint16"
        }
      ]
    },
    {
      "type": "error",
      "name": "InvalidVirtualReserves",
      "inputs": [
        {
          "name": "initialVirtualEth",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "initialVirtualToken",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "curveTokens",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "LaunchValueMismatch",
      "inputs": [
        {
          "name": "expectedValue",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "actualValue",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "LaunchesPaused",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NotInitialized",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NothingToClaim",
      "inputs": []
    },
    {
      "type": "error",
      "name": "Oversell",
      "inputs": [
        {
          "name": "tokensIn",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "tokensSold",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "PairFactoryMismatch",
      "inputs": [
        {
          "name": "expected",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "actual",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "PairLiquidityZero",
      "inputs": []
    },
    {
      "type": "error",
      "name": "PairNotCanonical",
      "inputs": [
        {
          "name": "expected",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "actual",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "PairSupplyNotZero",
      "inputs": [
        {
          "name": "totalSupply",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "PairTokenBalanceNotZero",
      "inputs": [
        {
          "name": "tokenBalance",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "PairTokenReserveNotZero",
      "inputs": [
        {
          "name": "tokenReserve",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "PairTokensMismatch",
      "inputs": [
        {
          "name": "token0",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "token1",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "ReentrancyGuardReentrantCall",
      "inputs": []
    },
    {
      "type": "error",
      "name": "SlippageExceeded",
      "inputs": [
        {
          "name": "minimum",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "actual",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "TokenTransferFailed",
      "inputs": [
        {
          "name": "token",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "recipient",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "TradingPaused",
      "inputs": []
    },
    {
      "type": "error",
      "name": "TransferRestricted",
      "inputs": [
        {
          "name": "operator",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "from",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "to",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "UnauthorizedCreatorClaim",
      "inputs": [
        {
          "name": "caller",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "creator",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "UnauthorizedCurve",
      "inputs": [
        {
          "name": "caller",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "UnauthorizedFactory",
      "inputs": [
        {
          "name": "caller",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "UnauthorizedPauseAuthority",
      "inputs": [
        {
          "name": "caller",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "authority",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "UnauthorizedProtocolClaim",
      "inputs": [
        {
          "name": "caller",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "treasury",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "UnauthorizedTimelock",
      "inputs": [
        {
          "name": "caller",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "timelock",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "UnknownEngine",
      "inputs": [
        {
          "name": "engineVersion",
          "type": "uint16",
          "internalType": "uint16"
        }
      ]
    },
    {
      "type": "error",
      "name": "WethTransferFailed",
      "inputs": [
        {
          "name": "recipient",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "WrongPhase",
      "inputs": [
        {
          "name": "expected",
          "type": "uint8",
          "internalType": "uint8"
        },
        {
          "name": "actual",
          "type": "uint8",
          "internalType": "uint8"
        }
      ]
    },
    {
      "type": "error",
      "name": "ZeroAddress",
      "inputs": [
        {
          "name": "field",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ]
    },
    {
      "type": "error",
      "name": "ZeroInput",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ZeroOutput",
      "inputs": []
    }
  ],
  "curve": [
    {
      "type": "function",
      "name": "buy",
      "inputs": [
        {
          "name": "tokenRecipient",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "refundRecipient",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "minTokensOut",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "deadline",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "tokensOut",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "ethGrossUsed",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "payable"
    },
    {
      "type": "function",
      "name": "claimCreatorFees",
      "inputs": [],
      "outputs": [
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "claimCreatorFeesTo",
      "inputs": [
        {
          "name": "recipient",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "claimRefund",
      "inputs": [],
      "outputs": [
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "claimRefundTo",
      "inputs": [
        {
          "name": "recipient",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "creator",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "pendingRefund",
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "phase",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint8",
          "internalType": "enum LaunchTypes.Phase"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "quoteBuy",
      "inputs": [
        {
          "name": "ethGross",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "ethGrossUsed",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "tokensOut",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "protocolFee",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "creatorFee",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "refund",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "graduates",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "quoteSell",
      "inputs": [
        {
          "name": "tokensIn",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "ethOut",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "ethGross",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "protocolFee",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "creatorFee",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "sell",
      "inputs": [
        {
          "name": "tokensIn",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "ethRecipient",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "minEthOut",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "deadline",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "ethOut",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "unclaimedCreatorFees",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "error",
      "name": "AccountingInvariantFailed",
      "inputs": [
        {
          "name": "balance",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "requiredBalance",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "AlreadyGraduated",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ArithmeticOverflow",
      "inputs": []
    },
    {
      "type": "error",
      "name": "CurveInvariantFailed",
      "inputs": [
        {
          "name": "virtualEth",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "virtualToken",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "invariant",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "DeadlineExpired",
      "inputs": [
        {
          "name": "deadline",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "currentTimestamp",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "DeveloperBuyCapExceeded",
      "inputs": [
        {
          "name": "tokensOut",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "maximumTokensOut",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "DivisionByZero",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EngineDisabled",
      "inputs": [
        {
          "name": "engineVersion",
          "type": "uint16",
          "internalType": "uint16"
        }
      ]
    },
    {
      "type": "error",
      "name": "EngineVersionMismatch",
      "inputs": [
        {
          "name": "expected",
          "type": "uint16",
          "internalType": "uint16"
        },
        {
          "name": "actual",
          "type": "uint16",
          "internalType": "uint16"
        }
      ]
    },
    {
      "type": "error",
      "name": "EthTransferFailed",
      "inputs": [
        {
          "name": "recipient",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "InvalidAuthority",
      "inputs": [
        {
          "name": "field",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "authority",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "InvalidRecipient",
      "inputs": [
        {
          "name": "field",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "recipient",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "LaunchesPaused",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NothingToClaim",
      "inputs": []
    },
    {
      "type": "error",
      "name": "Oversell",
      "inputs": [
        {
          "name": "tokensIn",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "tokensSold",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "PairFactoryMismatch",
      "inputs": [
        {
          "name": "expected",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "actual",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "PairLiquidityZero",
      "inputs": []
    },
    {
      "type": "error",
      "name": "PairNotCanonical",
      "inputs": [
        {
          "name": "expected",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "actual",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "PairSupplyNotZero",
      "inputs": [
        {
          "name": "totalSupply",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "PairTokenBalanceNotZero",
      "inputs": [
        {
          "name": "tokenBalance",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "PairTokenReserveNotZero",
      "inputs": [
        {
          "name": "tokenReserve",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "PairTokensMismatch",
      "inputs": [
        {
          "name": "token0",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "token1",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "ReentrancyGuardReentrantCall",
      "inputs": []
    },
    {
      "type": "error",
      "name": "SlippageExceeded",
      "inputs": [
        {
          "name": "minimum",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "actual",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "TokenTransferFailed",
      "inputs": [
        {
          "name": "token",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "recipient",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "TradingPaused",
      "inputs": []
    },
    {
      "type": "error",
      "name": "TransferRestricted",
      "inputs": [
        {
          "name": "operator",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "from",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "to",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "UnauthorizedCreatorClaim",
      "inputs": [
        {
          "name": "caller",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "creator",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "UnauthorizedCurve",
      "inputs": [
        {
          "name": "caller",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "UnauthorizedProtocolClaim",
      "inputs": [
        {
          "name": "caller",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "treasury",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "UnknownEngine",
      "inputs": [
        {
          "name": "engineVersion",
          "type": "uint16",
          "internalType": "uint16"
        }
      ]
    },
    {
      "type": "error",
      "name": "WethTransferFailed",
      "inputs": [
        {
          "name": "recipient",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "WrongPhase",
      "inputs": [
        {
          "name": "expected",
          "type": "uint8",
          "internalType": "uint8"
        },
        {
          "name": "actual",
          "type": "uint8",
          "internalType": "uint8"
        }
      ]
    },
    {
      "type": "error",
      "name": "ZeroInput",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ZeroOutput",
      "inputs": []
    }
  ],
  "token": [
    {
      "type": "function",
      "name": "allowance",
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "spender",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "approve",
      "inputs": [
        {
          "name": "spender",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "value",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "balanceOf",
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "decimals",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint8",
          "internalType": "uint8"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "name",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "string",
          "internalType": "string"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "symbol",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "string",
          "internalType": "string"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "totalSupply",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "error",
      "name": "ERC20InsufficientAllowance",
      "inputs": [
        {
          "name": "spender",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "allowance",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "needed",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "ERC20InsufficientBalance",
      "inputs": [
        {
          "name": "sender",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "balance",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "needed",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    }
  ],
  "router": [
    {
      "type": "function",
      "name": "WETH",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getAmountsOut",
      "inputs": [
        {
          "name": "amountIn",
          "type": "uint256"
        },
        {
          "name": "path",
          "type": "address[]"
        }
      ],
      "outputs": [
        {
          "name": "amounts",
          "type": "uint256[]"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "swapExactETHForTokens",
      "inputs": [
        {
          "name": "amountOutMin",
          "type": "uint256"
        },
        {
          "name": "path",
          "type": "address[]"
        },
        {
          "name": "to",
          "type": "address"
        },
        {
          "name": "deadline",
          "type": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "amounts",
          "type": "uint256[]"
        }
      ],
      "stateMutability": "payable"
    },
    {
      "type": "function",
      "name": "swapExactTokensForETH",
      "inputs": [
        {
          "name": "amountIn",
          "type": "uint256"
        },
        {
          "name": "amountOutMin",
          "type": "uint256"
        },
        {
          "name": "path",
          "type": "address[]"
        },
        {
          "name": "to",
          "type": "address"
        },
        {
          "name": "deadline",
          "type": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "amounts",
          "type": "uint256[]"
        }
      ],
      "stateMutability": "nonpayable"
    }
  ]
} as const;

export type BrowserAbiName = keyof typeof browserAbis;

export type ReviewedDeployment = {
  deploymentId: string; chainId: number; name: string; enabled: boolean; factory: string | null;
  explorerBase: string | null; weth: string | null; uniswapV2Factory: string | null;
  uniswapV2Router02: string | null;
};

export const reviewedDeployments: readonly ReviewedDeployment[] = [
  {
    "deploymentId": "robinhood-mainnet",
    "chainId": 4663,
    "name": "Robinhood Chain",
    "enabled": false,
    "factory": null,
    "explorerBase": "https://robinhoodchain.blockscout.com",
    "weth": "0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73",
    "uniswapV2Factory": "0x8bcEaA40B9AcdfAedF85AdF4FF01F5Ad6517937f",
    "uniswapV2Router02": "0x89e5DB8B5aA49aA85AC63f691524311AEB649eba"
  },
  {
    "deploymentId": "robinhood-testnet-v1",
    "chainId": 46630,
    "name": "Robinhood Chain Testnet",
    "enabled": true,
    "factory": "0xedddb61a53226ffdc6ecf7c042b803e769168d55",
    "explorerBase": "https://explorer.testnet.chain.robinhood.com",
    "weth": "0xcc02c43352422cc5ce27d8f222302050aeecbd6f",
    "uniswapV2Factory": "0x76748a790c21335ac0a170504e362b8859c514f5",
    "uniswapV2Router02": null
  }
];
