// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AggregationDirty struct {
	ChainID           int64
	TokenAddress      Address
	Generation        int64
	ClaimedGeneration pgtype.Int8
	ClaimedAt         pgtype.Timestamptz
	ClaimedBy         pgtype.Text
}

type Candle struct {
	ChainID         int64
	TokenAddress    Address
	Interval        string
	BucketStartTime pgtype.Timestamptz
	OpenPriceWad    Uint256
	HighPriceWad    Uint256
	LowPriceWad     Uint256
	ClosePriceWad   Uint256
	GrossEthVolume  Uint256
	TokenVolume     Uint256
	TradeCount      int32
}

type CreatorFeeClaim struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	TokenAddress     Address
	Creator          Address
	Amount           Uint256
}

type EngineConfiguration struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	EngineVersion    int32
	Implementation   Address
	Enabled          bool
}

type FutureDefaultsConfiguration struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	ConfigHash       Hash
}

type FutureTreasuryConfiguration struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	PreviousTreasury Address
	NewTreasury      Address
}

type Graduation struct {
	ChainID           int64
	BlockNumber       int64
	BlockHash         Hash
	BlockTime         pgtype.Timestamptz
	TransactionIndex  int32
	TxHash            Hash
	LogIndex          int32
	TokenAddress      Address
	LpPair            Address
	EthToPool         Uint256
	TokensToPool      Uint256
	LpLiquidityBurned Uint256
}

type HolderBalance struct {
	ChainID                  int64
	TokenAddress             Address
	HolderAddress            Address
	Balance                  Uint256
	FirstAcquiredBlockNumber pgtype.Int8
}

type IndexedBlock struct {
	ChainID        int64
	BlockNumber    int64
	BlockHash      Hash
	ParentHash     Hash
	BlockTime      pgtype.Timestamptz
	FinalityStatus string
}

type IndexerReorg struct {
	ReorgID              int64
	ChainID              int64
	DeploymentID         string
	DetectedTipNumber    int64
	DetectedTipHash      Hash
	CommonAncestorNumber int64
	CommonAncestorHash   Hash
	Depth                int64
	DetectedAt           pgtype.Timestamptz
	Outcome              string
	CompletedAt          pgtype.Timestamptz
}

type LaunchFeeClaim struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	Treasury         Address
	Amount           Uint256
}

type LaunchPauseEvent struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	Paused           bool
}

type MarketTrade struct {
	ChainID           int64
	TokenAddress      Address
	BlockNumber       int64
	BlockTime         pgtype.Timestamptz
	TransactionIndex  int32
	TxHash            Hash
	LogIndex          int32
	Source            string
	SideBuy           bool
	Trader            Address
	ExecutionPriceWad pgtype.Numeric
	SpotPriceWad      pgtype.Numeric
	GrossEthVolume    Uint256
	TokenVolume       Uint256
	Finality          string
}

type PoolBurn struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	PairAddress      Address
	Sender           Address
	Amount0          Uint256
	Amount1          Uint256
	ToAddress        Address
}

type PoolMint struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	PairAddress      Address
	Sender           Address
	Amount0          Uint256
	Amount1          Uint256
}

type PoolSwap struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	PairAddress      Address
	Sender           Address
	Amount0In        Uint256
	Amount1In        Uint256
	Amount0Out       Uint256
	Amount1Out       Uint256
	ToAddress        Address
}

type PoolSync struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	PairAddress      Address
	Reserve0         Uint256
	Reserve1         Uint256
}

type ProtocolDaily struct {
	ChainID          int64
	Day              pgtype.Date
	VolumeEthWad     Uint256
	VolumeUsd        pgtype.Numeric
	LaunchesCount    int32
	TradesCount      int32
	GraduationsCount int32
}

type ProtocolFeeClaim struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	TokenAddress     Address
	Treasury         Address
	Amount           Uint256
}

type ProtocolStat struct {
	ChainID             int64
	Volume24hEthWad     Uint256
	Volume24hUsd        pgtype.Numeric
	VolumeAllTimeEthWad Uint256
	VolumeAllTimeUsd    pgtype.Numeric
	Launches24h         int32
	LaunchesAllTime     int32
	Trades24h           int32
	TradesAllTime       int64
	Graduations24h      int32
	GraduationsAllTime  int32
	UpdatedAt           pgtype.Timestamptz
}

type RefundClaim struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	TokenAddress     Address
	Account          Address
	Amount           Uint256
}

type RefundCredit struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	TokenAddress     Address
	Account          Address
	Amount           Uint256
}

type SyncState struct {
	ChainID         int64
	DeploymentID    string
	ObservedNumber  pgtype.Int8
	ObservedHash    *Hash
	ObservedAt      pgtype.Timestamptz
	SafeNumber      pgtype.Int8
	SafeHash        *Hash
	SafeAt          pgtype.Timestamptz
	FinalizedNumber pgtype.Int8
	FinalizedHash   *Hash
	FinalizedAt     pgtype.Timestamptz
}

type Token struct {
	ChainID               int64
	TokenAddress          Address
	CurveAddress          Address
	LpPair                Address
	Weth                  Address
	Creator               Address
	ProtocolTreasury      Address
	EngineVersion         int32
	Name                  string
	Symbol                string
	TotalSupply           Uint256
	InitialVirtualEth     Uint256
	InitialVirtualToken   Uint256
	CurveTokens           Uint256
	LpTokens              Uint256
	GraduationEth         Uint256
	TradeFeeBps           int32
	ProtocolShareBps      int32
	LaunchBlockNumber     int64
	LaunchBlockHash       Hash
	LaunchBlockTime       pgtype.Timestamptz
	LaunchTxHash          Hash
	LaunchLogIndex        int32
	Phase                 string
	GraduationBlockNumber pgtype.Int8
	GraduationBlockHash   *Hash
	GraduationBlockTime   pgtype.Timestamptz
	GraduationTxHash      *Hash
	GraduationLogIndex    pgtype.Int4
	TokenIsToken0         bool
	SortMarketCapEthWad   Uint256
	SortVolume24hEthWad   Uint256
}

type TokenImage struct {
	ChainID        int64
	TokenAddress   Address
	ContentType    string
	Content        []byte
	ByteSize       int32
	Sha256         Hash
	Revision       int64
	UpdatedAt      pgtype.Timestamptz
	ContentID      pgtype.Int8
	LaunchTxHash   *Hash
	LaunchLogIndex pgtype.Int4
}

type TokenLaunch struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	TokenAddress     Address
	CurveAddress     Address
	Creator          Address
	LpPair           Address
	Weth             Address
	ProtocolTreasury Address
	EngineVersion    int32
	Name             string
	Symbol           string
	TotalSupply      Uint256
	VirtualEth       Uint256
	VirtualToken     Uint256
	CurveTokens      Uint256
	LpTokens         Uint256
	GraduationEth    Uint256
	LaunchFeePaid    Uint256
	TradeFeeBps      int32
	ProtocolShareBps int32
}

type TokenMetadatum struct {
	ChainID        int64
	TokenAddress   Address
	Description    pgtype.Text
	ImageUrl       pgtype.Text
	XUrl           pgtype.Text
	TelegramUrl    pgtype.Text
	UpdatedAt      pgtype.Timestamptz
	Revision       int64
	ContentID      pgtype.Int8
	LaunchTxHash   *Hash
	LaunchLogIndex pgtype.Int4
}

type TokenReserf struct {
	ChainID           int64
	TokenAddress      Address
	ReserveSource     string
	EthReserve        Uint256
	TokenReserve      Uint256
	SourceBlockNumber int64
	SourceBlockHash   Hash
	SourceBlockTime   pgtype.Timestamptz
	SourceTxHash      Hash
	SourceLogIndex    int32
}

type TokenStat struct {
	ChainID           int64
	TokenAddress      Address
	SpotPriceEthWad   Uint256
	MarketCapEthWad   Uint256
	FdvEthWad         Uint256
	LiquidityEthWad   Uint256
	AthPriceEthWad    Uint256
	AthAt             pgtype.Timestamptz
	Volume24hEthWad   Uint256
	PriceChange24hBps int64
	HolderCount       int32
	SpotPriceUsd      pgtype.Numeric
	MarketCapUsd      pgtype.Numeric
	FdvUsd            pgtype.Numeric
	LiquidityUsd      pgtype.Numeric
	AthUsd            pgtype.Numeric
	Volume24hUsd      pgtype.Numeric
	UpdatedAt         pgtype.Timestamptz
}

type Trade struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	TokenAddress     Address
	Trader           Address
	IsBuy            bool
	EthGross         Uint256
	EthRefund        Uint256
	TokenAmount      Uint256
	ProtocolFee      Uint256
	CreatorFee       Uint256
	NewEthReserve    Uint256
	NewTokenReserve  Uint256
}

type TradingPauseEvent struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	Paused           bool
}

type Transfer struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	TokenAddress     Address
	FromAddress      Address
	ToAddress        Address
	Value            Uint256
}
