// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: read.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProtocolStats = `-- name: GetProtocolStats :one
SELECT volume_24h_eth_wad, volume_all_time_eth_wad, launches_24h,
       launches_all_time, trades_24h, trades_all_time, graduations_24h,
       graduations_all_time, updated_at
FROM protocol_stats
WHERE chain_id = $1
`

type GetProtocolStatsRow struct {
	Volume24hEthWad     Uint256
	VolumeAllTimeEthWad Uint256
	Launches24h         int32
	LaunchesAllTime     int32
	Trades24h           int32
	TradesAllTime       int64
	Graduations24h      int32
	GraduationsAllTime  int32
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) GetProtocolStats(ctx context.Context, chainID int64) (GetProtocolStatsRow, error) {
	row := q.db.QueryRow(ctx, getProtocolStats, chainID)
	var i GetProtocolStatsRow
	err := row.Scan(
		&i.Volume24hEthWad,
		&i.VolumeAllTimeEthWad,
		&i.Launches24h,
		&i.LaunchesAllTime,
		&i.Trades24h,
		&i.TradesAllTime,
		&i.Graduations24h,
		&i.GraduationsAllTime,
		&i.UpdatedAt,
	)
	return i, err
}

const getTokenDetail = `-- name: GetTokenDetail :one
SELECT t.token_address, t.curve_address, t.lp_pair, t.weth, t.creator,
       t.protocol_treasury, t.engine_version, t.name, t.symbol, t.phase,
       t.launch_block_number, t.launch_block_time, t.total_supply,
       t.initial_virtual_eth, t.initial_virtual_token, t.curve_tokens,
       t.lp_tokens, t.graduation_eth, t.trade_fee_bps, t.protocol_share_bps,
       COALESCE(r.reserve_source, 'curve')::text AS reserve_source,
       COALESCE(r.eth_reserve, t.initial_virtual_eth) AS eth_reserve,
       COALESCE(r.token_reserve, t.initial_virtual_token) AS token_reserve,
       CASE WHEN t.phase = 'graduated' THEN t.graduation_eth
            ELSE GREATEST(COALESCE(r.eth_reserve, t.initial_virtual_eth) - t.initial_virtual_eth, 0::numeric)
       END::numeric(78, 0) AS real_curve_eth,
       CASE WHEN t.phase = 'graduated' THEN 10000
            WHEN t.graduation_eth = 0 THEN 0
            ELSE LEAST(10000, floor(GREATEST(COALESCE(r.eth_reserve, t.initial_virtual_eth) - t.initial_virtual_eth, 0::numeric) * 10000 / t.graduation_eth))
       END::integer AS graduation_progress_bps,
       COALESCE(r.source_block_number, t.launch_block_number) AS reserve_block_number,
       COALESCE(r.source_block_hash, t.launch_block_hash) AS reserve_block_hash,
       COALESCE(r.source_block_time, t.launch_block_time) AS reserve_block_time,
       m.description, m.image_url, m.x_url, m.telegram_url,
       COALESCE(s.spot_price_eth_wad, 0::numeric) AS spot_price_eth_wad,
       COALESCE(s.market_cap_eth_wad, 0::numeric) AS market_cap_eth_wad,
       COALESCE(s.fdv_eth_wad, 0::numeric) AS fdv_eth_wad,
       COALESCE(s.liquidity_eth_wad, 0::numeric) AS liquidity_eth_wad,
       COALESCE(s.ath_price_eth_wad, 0::numeric) AS ath_price_eth_wad,
       COALESCE(s.ath_at, t.launch_block_time) AS ath_at,
       COALESCE(s.volume_24h_eth_wad, 0::numeric) AS volume_24h_eth_wad,
       COALESCE(s.price_change_24h_bps, 0)::bigint AS price_change_24h_bps,
       COALESCE(s.holder_count, 0)::bigint AS holder_count
FROM tokens AS t
LEFT JOIN token_reserves AS r USING (chain_id, token_address)
LEFT JOIN token_metadata AS m
  ON m.chain_id = t.chain_id AND m.token_address = t.token_address
 AND m.launch_tx_hash = t.launch_tx_hash AND m.launch_log_index = t.launch_log_index
LEFT JOIN token_stats AS s ON s.chain_id = t.chain_id AND s.token_address = t.token_address
WHERE t.chain_id = $1
  AND t.token_address = $2
`

type GetTokenDetailParams struct {
	ChainID      int64
	TokenAddress Address
}

type GetTokenDetailRow struct {
	TokenAddress          Address
	CurveAddress          Address
	LpPair                Address
	Weth                  Address
	Creator               Address
	ProtocolTreasury      Address
	EngineVersion         int32
	Name                  string
	Symbol                string
	Phase                 string
	LaunchBlockNumber     int64
	LaunchBlockTime       pgtype.Timestamptz
	TotalSupply           Uint256
	InitialVirtualEth     Uint256
	InitialVirtualToken   Uint256
	CurveTokens           Uint256
	LpTokens              Uint256
	GraduationEth         Uint256
	TradeFeeBps           int32
	ProtocolShareBps      int32
	ReserveSource         string
	EthReserve            Uint256
	TokenReserve          Uint256
	RealCurveEth          pgtype.Numeric
	GraduationProgressBps int32
	ReserveBlockNumber    int64
	ReserveBlockHash      Hash
	ReserveBlockTime      pgtype.Timestamptz
	Description           pgtype.Text
	ImageUrl              pgtype.Text
	XUrl                  pgtype.Text
	TelegramUrl           pgtype.Text
	SpotPriceEthWad       Uint256
	MarketCapEthWad       Uint256
	FdvEthWad             Uint256
	LiquidityEthWad       Uint256
	AthPriceEthWad        Uint256
	AthAt                 pgtype.Timestamptz
	Volume24hEthWad       Uint256
	PriceChange24hBps     int64
	HolderCount           int64
}

func (q *Queries) GetTokenDetail(ctx context.Context, arg GetTokenDetailParams) (GetTokenDetailRow, error) {
	row := q.db.QueryRow(ctx, getTokenDetail, arg.ChainID, arg.TokenAddress)
	var i GetTokenDetailRow
	err := row.Scan(
		&i.TokenAddress,
		&i.CurveAddress,
		&i.LpPair,
		&i.Weth,
		&i.Creator,
		&i.ProtocolTreasury,
		&i.EngineVersion,
		&i.Name,
		&i.Symbol,
		&i.Phase,
		&i.LaunchBlockNumber,
		&i.LaunchBlockTime,
		&i.TotalSupply,
		&i.InitialVirtualEth,
		&i.InitialVirtualToken,
		&i.CurveTokens,
		&i.LpTokens,
		&i.GraduationEth,
		&i.TradeFeeBps,
		&i.ProtocolShareBps,
		&i.ReserveSource,
		&i.EthReserve,
		&i.TokenReserve,
		&i.RealCurveEth,
		&i.GraduationProgressBps,
		&i.ReserveBlockNumber,
		&i.ReserveBlockHash,
		&i.ReserveBlockTime,
		&i.Description,
		&i.ImageUrl,
		&i.XUrl,
		&i.TelegramUrl,
		&i.SpotPriceEthWad,
		&i.MarketCapEthWad,
		&i.FdvEthWad,
		&i.LiquidityEthWad,
		&i.AthPriceEthWad,
		&i.AthAt,
		&i.Volume24hEthWad,
		&i.PriceChange24hBps,
		&i.HolderCount,
	)
	return i, err
}

const getTokenQuoteState = `-- name: GetTokenQuoteState :one
SELECT t.phase, t.total_supply, t.curve_tokens, t.lp_tokens, t.graduation_eth,
       t.initial_virtual_eth, t.initial_virtual_token, t.trade_fee_bps,
       t.protocol_share_bps,
       COALESCE(r.eth_reserve, t.initial_virtual_eth) AS eth_reserve,
       COALESCE(r.token_reserve, t.initial_virtual_token) AS token_reserve,
       COALESCE(r.source_block_number, t.launch_block_number) AS reserve_block_number,
       COALESCE(r.source_block_hash, t.launch_block_hash) AS reserve_block_hash
FROM tokens AS t
LEFT JOIN token_reserves AS r USING (chain_id, token_address)
WHERE t.chain_id = $1
  AND t.token_address = $2
`

type GetTokenQuoteStateParams struct {
	ChainID      int64
	TokenAddress Address
}

type GetTokenQuoteStateRow struct {
	Phase               string
	TotalSupply         Uint256
	CurveTokens         Uint256
	LpTokens            Uint256
	GraduationEth       Uint256
	InitialVirtualEth   Uint256
	InitialVirtualToken Uint256
	TradeFeeBps         int32
	ProtocolShareBps    int32
	EthReserve          Uint256
	TokenReserve        Uint256
	ReserveBlockNumber  int64
	ReserveBlockHash    Hash
}

func (q *Queries) GetTokenQuoteState(ctx context.Context, arg GetTokenQuoteStateParams) (GetTokenQuoteStateRow, error) {
	row := q.db.QueryRow(ctx, getTokenQuoteState, arg.ChainID, arg.TokenAddress)
	var i GetTokenQuoteStateRow
	err := row.Scan(
		&i.Phase,
		&i.TotalSupply,
		&i.CurveTokens,
		&i.LpTokens,
		&i.GraduationEth,
		&i.InitialVirtualEth,
		&i.InitialVirtualToken,
		&i.TradeFeeBps,
		&i.ProtocolShareBps,
		&i.EthReserve,
		&i.TokenReserve,
		&i.ReserveBlockNumber,
		&i.ReserveBlockHash,
	)
	return i, err
}

const listCandlesAggregated = `-- name: ListCandlesAggregated :many
SELECT c.group_start AS bucket_start_time,
       (array_agg(c.open_price_wad ORDER BY c.bucket_start_time ASC))[1] AS open_price_wad,
       max(c.high_price_wad) AS high_price_wad,
       min(c.low_price_wad) AS low_price_wad,
       (array_agg(c.close_price_wad ORDER BY c.bucket_start_time DESC))[1] AS close_price_wad,
       sum(c.gross_eth_volume)::numeric AS gross_eth_volume,
       sum(c.token_volume)::numeric AS token_volume,
       sum(c.trade_count)::BIGINT AS trade_count
FROM (
    SELECT source.bucket_start_time, source.open_price_wad, source.high_price_wad,
           source.low_price_wad, source.close_price_wad, source.gross_eth_volume,
           source.token_volume, source.trade_count,
           CASE WHEN $1::text = '6h'
                THEN date_trunc('day', source.bucket_start_time, 'UTC')
                     + floor(extract(hour FROM source.bucket_start_time AT TIME ZONE 'UTC') / 6) * interval '6 hours'
                ELSE date_trunc('day', source.bucket_start_time, 'UTC') END AS group_start
    FROM candles AS source
    WHERE source.chain_id = $2
      AND source.token_address = $3
      AND source.interval = $4
      AND source.bucket_start_time >= $5
      AND source.bucket_start_time < $6
) AS c
GROUP BY c.group_start
ORDER BY c.group_start ASC
LIMIT $7::integer
`

type ListCandlesAggregatedParams struct {
	TargetInterval string
	ChainID        int64
	TokenAddress   Address
	SourceInterval string
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
	PageSize       int32
}

type ListCandlesAggregatedRow struct {
	BucketStartTime interface{}
	OpenPriceWad    interface{}
	HighPriceWad    interface{}
	LowPriceWad     interface{}
	ClosePriceWad   interface{}
	GrossEthVolume  pgtype.Numeric
	TokenVolume     pgtype.Numeric
	TradeCount      int64
}

// Each row is keyed by its UTC-aligned group start (not the first stored source bucket), so
// sparse groups report a stable timestamp and the next-page cursor can skip a whole group.
func (q *Queries) ListCandlesAggregated(ctx context.Context, arg ListCandlesAggregatedParams) ([]ListCandlesAggregatedRow, error) {
	rows, err := q.db.Query(ctx, listCandlesAggregated,
		arg.TargetInterval,
		arg.ChainID,
		arg.TokenAddress,
		arg.SourceInterval,
		arg.FromTime,
		arg.ToTime,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCandlesAggregatedRow{}
	for rows.Next() {
		var i ListCandlesAggregatedRow
		if err := rows.Scan(
			&i.BucketStartTime,
			&i.OpenPriceWad,
			&i.HighPriceWad,
			&i.LowPriceWad,
			&i.ClosePriceWad,
			&i.GrossEthVolume,
			&i.TokenVolume,
			&i.TradeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketTrades = `-- name: ListMarketTrades :many
SELECT source, COALESCE(encode(trader, 'hex'), '')::text AS trader_hex,
       side_buy, execution_price_wad, spot_price_wad,
       gross_eth_volume, token_volume, block_number, transaction_index,
       tx_hash, log_index, block_time, finality
FROM market_trades
WHERE chain_id = $1
  AND token_address = $2
  AND ($3::bigint IS NULL OR
       (block_number, transaction_index, log_index) <
       ($3::bigint, $4::integer, $5::integer))
ORDER BY block_number DESC, transaction_index DESC, log_index DESC
LIMIT $6::integer
`

type ListMarketTradesParams struct {
	ChainID               int64
	TokenAddress          Address
	AfterBlock            pgtype.Int8
	AfterTransactionIndex pgtype.Int4
	AfterLogIndex         pgtype.Int4
	PageSize              int32
}

type ListMarketTradesRow struct {
	Source            string
	TraderHex         string
	SideBuy           bool
	ExecutionPriceWad pgtype.Numeric
	SpotPriceWad      pgtype.Numeric
	GrossEthVolume    Uint256
	TokenVolume       Uint256
	BlockNumber       int64
	TransactionIndex  int32
	TxHash            Hash
	LogIndex          int32
	BlockTime         pgtype.Timestamptz
	Finality          string
}

func (q *Queries) ListMarketTrades(ctx context.Context, arg ListMarketTradesParams) ([]ListMarketTradesRow, error) {
	rows, err := q.db.Query(ctx, listMarketTrades,
		arg.ChainID,
		arg.TokenAddress,
		arg.AfterBlock,
		arg.AfterTransactionIndex,
		arg.AfterLogIndex,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketTradesRow{}
	for rows.Next() {
		var i ListMarketTradesRow
		if err := rows.Scan(
			&i.Source,
			&i.TraderHex,
			&i.SideBuy,
			&i.ExecutionPriceWad,
			&i.SpotPriceWad,
			&i.GrossEthVolume,
			&i.TokenVolume,
			&i.BlockNumber,
			&i.TransactionIndex,
			&i.TxHash,
			&i.LogIndex,
			&i.BlockTime,
			&i.Finality,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProtocolDaily = `-- name: ListProtocolDaily :many
SELECT day, volume_eth_wad, launches_count, trades_count, graduations_count
FROM protocol_daily
WHERE chain_id = $1
  AND day >= $2
  AND day <= $3
ORDER BY day ASC
LIMIT $4::integer
`

type ListProtocolDailyParams struct {
	ChainID  int64
	FromDay  pgtype.Date
	ToDay    pgtype.Date
	PageSize int32
}

type ListProtocolDailyRow struct {
	Day              pgtype.Date
	VolumeEthWad     Uint256
	LaunchesCount    int32
	TradesCount      int32
	GraduationsCount int32
}

func (q *Queries) ListProtocolDaily(ctx context.Context, arg ListProtocolDailyParams) ([]ListProtocolDailyRow, error) {
	rows, err := q.db.Query(ctx, listProtocolDaily,
		arg.ChainID,
		arg.FromDay,
		arg.ToDay,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProtocolDailyRow{}
	for rows.Next() {
		var i ListProtocolDailyRow
		if err := rows.Scan(
			&i.Day,
			&i.VolumeEthWad,
			&i.LaunchesCount,
			&i.TradesCount,
			&i.GraduationsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoredCandles = `-- name: ListStoredCandles :many
SELECT bucket_start_time, open_price_wad, high_price_wad, low_price_wad,
       close_price_wad, gross_eth_volume, token_volume, trade_count
FROM candles
WHERE chain_id = $1
  AND token_address = $2
  AND interval = $3
  AND bucket_start_time >= $4
  AND bucket_start_time < $5
  AND ($6::timestamptz IS NULL OR bucket_start_time > $6::timestamptz)
ORDER BY bucket_start_time ASC
LIMIT $7::integer
`

type ListStoredCandlesParams struct {
	ChainID      int64
	TokenAddress Address
	Interval     string
	FromTime     pgtype.Timestamptz
	ToTime       pgtype.Timestamptz
	AfterTime    pgtype.Timestamptz
	PageSize     int32
}

type ListStoredCandlesRow struct {
	BucketStartTime pgtype.Timestamptz
	OpenPriceWad    Uint256
	HighPriceWad    Uint256
	LowPriceWad     Uint256
	ClosePriceWad   Uint256
	GrossEthVolume  Uint256
	TokenVolume     Uint256
	TradeCount      int32
}

func (q *Queries) ListStoredCandles(ctx context.Context, arg ListStoredCandlesParams) ([]ListStoredCandlesRow, error) {
	rows, err := q.db.Query(ctx, listStoredCandles,
		arg.ChainID,
		arg.TokenAddress,
		arg.Interval,
		arg.FromTime,
		arg.ToTime,
		arg.AfterTime,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoredCandlesRow{}
	for rows.Next() {
		var i ListStoredCandlesRow
		if err := rows.Scan(
			&i.BucketStartTime,
			&i.OpenPriceWad,
			&i.HighPriceWad,
			&i.LowPriceWad,
			&i.ClosePriceWad,
			&i.GrossEthVolume,
			&i.TokenVolume,
			&i.TradeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenCardsMarketCap = `-- name: ListTokenCardsMarketCap :many
SELECT t.token_address, t.name, t.symbol, t.phase, t.launch_block_number, t.launch_block_time, t.total_supply,
       t.sort_market_cap_eth_wad AS market_cap_eth_wad, t.sort_volume_24h_eth_wad AS volume_24h_eth_wad,
       COALESCE(s.holder_count, 0)::BIGINT AS holder_count, m.description, m.image_url, m.x_url, m.telegram_url, t.launch_block_hash
FROM tokens AS t
LEFT JOIN token_metadata AS m ON m.chain_id = t.chain_id AND m.token_address = t.token_address
    AND m.launch_tx_hash = t.launch_tx_hash AND m.launch_log_index = t.launch_log_index
LEFT JOIN token_stats AS s ON s.chain_id = t.chain_id AND s.token_address = t.token_address
WHERE t.chain_id = $1 AND t.phase = $2
  AND ($3::text = '' OR lower(t.name) LIKE lower($3::text) || '%' OR lower(t.symbol) LIKE lower($3::text) || '%' OR encode(t.token_address, 'hex') = lower(CASE WHEN left($3::text,2)='0x' THEN substr($3::text,3) ELSE $3::text END))
  AND ($4::numeric IS NULL OR (t.sort_market_cap_eth_wad, t.token_address) < ($4::numeric, $5::bytea))
ORDER BY t.sort_market_cap_eth_wad DESC, t.token_address DESC LIMIT $6::integer
`

type ListTokenCardsMarketCapParams struct {
	ChainID      int64
	Phase        string
	Search       string
	AfterMetric  pgtype.Numeric
	AfterAddress []byte
	PageSize     int32
}

type ListTokenCardsMarketCapRow struct {
	TokenAddress      Address
	Name              string
	Symbol            string
	Phase             string
	LaunchBlockNumber int64
	LaunchBlockTime   pgtype.Timestamptz
	TotalSupply       Uint256
	MarketCapEthWad   Uint256
	Volume24hEthWad   Uint256
	HolderCount       int64
	Description       pgtype.Text
	ImageUrl          pgtype.Text
	XUrl              pgtype.Text
	TelegramUrl       pgtype.Text
	LaunchBlockHash   Hash
}

// Metric sorts walk tokens_phase_*_cursor_idx; the sort columns mirror token_stats (0 when
// no stats row exists) through triggers, see migration 00014.
func (q *Queries) ListTokenCardsMarketCap(ctx context.Context, arg ListTokenCardsMarketCapParams) ([]ListTokenCardsMarketCapRow, error) {
	rows, err := q.db.Query(ctx, listTokenCardsMarketCap,
		arg.ChainID,
		arg.Phase,
		arg.Search,
		arg.AfterMetric,
		arg.AfterAddress,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokenCardsMarketCapRow{}
	for rows.Next() {
		var i ListTokenCardsMarketCapRow
		if err := rows.Scan(
			&i.TokenAddress,
			&i.Name,
			&i.Symbol,
			&i.Phase,
			&i.LaunchBlockNumber,
			&i.LaunchBlockTime,
			&i.TotalSupply,
			&i.MarketCapEthWad,
			&i.Volume24hEthWad,
			&i.HolderCount,
			&i.Description,
			&i.ImageUrl,
			&i.XUrl,
			&i.TelegramUrl,
			&i.LaunchBlockHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenCardsNewest = `-- name: ListTokenCardsNewest :many
SELECT t.token_address, t.name, t.symbol, t.phase,
       t.launch_block_number, t.launch_block_time, t.total_supply,
       COALESCE(s.market_cap_eth_wad, 0::numeric) AS market_cap_eth_wad,
       COALESCE(s.volume_24h_eth_wad, 0::numeric) AS volume_24h_eth_wad,
       COALESCE(s.holder_count, 0)::BIGINT AS holder_count,
       m.description, m.image_url, m.x_url, m.telegram_url,
       t.launch_block_hash
FROM tokens AS t
LEFT JOIN token_metadata AS m
  ON m.chain_id = t.chain_id AND m.token_address = t.token_address
 AND m.launch_tx_hash = t.launch_tx_hash AND m.launch_log_index = t.launch_log_index
LEFT JOIN token_stats AS s
  ON s.chain_id = t.chain_id AND s.token_address = t.token_address
WHERE t.chain_id = $1
  AND t.phase = $2
  AND ($3::text = '' OR lower(t.name) LIKE lower($3::text) || '%'
       OR lower(t.symbol) LIKE lower($3::text) || '%'
       OR encode(t.token_address, 'hex') = lower(CASE WHEN left($3::text,2)='0x' THEN substr($3::text,3) ELSE $3::text END))
  AND ($4::bigint IS NULL
       OR (t.launch_block_number, t.token_address) < ($4::bigint, $5::bytea))
ORDER BY t.launch_block_number DESC, t.token_address DESC
LIMIT $6::integer
`

type ListTokenCardsNewestParams struct {
	ChainID      int64
	Phase        string
	Search       string
	AfterBlock   pgtype.Int8
	AfterAddress []byte
	PageSize     int32
}

type ListTokenCardsNewestRow struct {
	TokenAddress      Address
	Name              string
	Symbol            string
	Phase             string
	LaunchBlockNumber int64
	LaunchBlockTime   pgtype.Timestamptz
	TotalSupply       Uint256
	MarketCapEthWad   Uint256
	Volume24hEthWad   Uint256
	HolderCount       int64
	Description       pgtype.Text
	ImageUrl          pgtype.Text
	XUrl              pgtype.Text
	TelegramUrl       pgtype.Text
	LaunchBlockHash   Hash
}

func (q *Queries) ListTokenCardsNewest(ctx context.Context, arg ListTokenCardsNewestParams) ([]ListTokenCardsNewestRow, error) {
	rows, err := q.db.Query(ctx, listTokenCardsNewest,
		arg.ChainID,
		arg.Phase,
		arg.Search,
		arg.AfterBlock,
		arg.AfterAddress,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokenCardsNewestRow{}
	for rows.Next() {
		var i ListTokenCardsNewestRow
		if err := rows.Scan(
			&i.TokenAddress,
			&i.Name,
			&i.Symbol,
			&i.Phase,
			&i.LaunchBlockNumber,
			&i.LaunchBlockTime,
			&i.TotalSupply,
			&i.MarketCapEthWad,
			&i.Volume24hEthWad,
			&i.HolderCount,
			&i.Description,
			&i.ImageUrl,
			&i.XUrl,
			&i.TelegramUrl,
			&i.LaunchBlockHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenCardsOldest = `-- name: ListTokenCardsOldest :many
SELECT t.token_address, t.name, t.symbol, t.phase, t.launch_block_number, t.launch_block_time, t.total_supply,
       COALESCE(s.market_cap_eth_wad, 0::numeric) AS market_cap_eth_wad, COALESCE(s.volume_24h_eth_wad, 0::numeric) AS volume_24h_eth_wad,
       COALESCE(s.holder_count, 0)::BIGINT AS holder_count, m.description, m.image_url, m.x_url, m.telegram_url, t.launch_block_hash
FROM tokens AS t
LEFT JOIN token_metadata AS m ON m.chain_id = t.chain_id AND m.token_address = t.token_address
    AND m.launch_tx_hash = t.launch_tx_hash AND m.launch_log_index = t.launch_log_index
LEFT JOIN token_stats AS s ON s.chain_id = t.chain_id AND s.token_address = t.token_address
WHERE t.chain_id = $1 AND t.phase = $2
  AND ($3::text = '' OR lower(t.name) LIKE lower($3::text) || '%' OR lower(t.symbol) LIKE lower($3::text) || '%' OR encode(t.token_address, 'hex') = lower(CASE WHEN left($3::text,2)='0x' THEN substr($3::text,3) ELSE $3::text END))
  AND ($4::bigint IS NULL OR (t.launch_block_number, t.token_address) > ($4::bigint, $5::bytea))
ORDER BY t.launch_block_number ASC, t.token_address ASC LIMIT $6::integer
`

type ListTokenCardsOldestParams struct {
	ChainID      int64
	Phase        string
	Search       string
	AfterBlock   pgtype.Int8
	AfterAddress []byte
	PageSize     int32
}

type ListTokenCardsOldestRow struct {
	TokenAddress      Address
	Name              string
	Symbol            string
	Phase             string
	LaunchBlockNumber int64
	LaunchBlockTime   pgtype.Timestamptz
	TotalSupply       Uint256
	MarketCapEthWad   Uint256
	Volume24hEthWad   Uint256
	HolderCount       int64
	Description       pgtype.Text
	ImageUrl          pgtype.Text
	XUrl              pgtype.Text
	TelegramUrl       pgtype.Text
	LaunchBlockHash   Hash
}

func (q *Queries) ListTokenCardsOldest(ctx context.Context, arg ListTokenCardsOldestParams) ([]ListTokenCardsOldestRow, error) {
	rows, err := q.db.Query(ctx, listTokenCardsOldest,
		arg.ChainID,
		arg.Phase,
		arg.Search,
		arg.AfterBlock,
		arg.AfterAddress,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokenCardsOldestRow{}
	for rows.Next() {
		var i ListTokenCardsOldestRow
		if err := rows.Scan(
			&i.TokenAddress,
			&i.Name,
			&i.Symbol,
			&i.Phase,
			&i.LaunchBlockNumber,
			&i.LaunchBlockTime,
			&i.TotalSupply,
			&i.MarketCapEthWad,
			&i.Volume24hEthWad,
			&i.HolderCount,
			&i.Description,
			&i.ImageUrl,
			&i.XUrl,
			&i.TelegramUrl,
			&i.LaunchBlockHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenCardsVolume = `-- name: ListTokenCardsVolume :many
SELECT t.token_address, t.name, t.symbol, t.phase, t.launch_block_number, t.launch_block_time, t.total_supply,
       t.sort_market_cap_eth_wad AS market_cap_eth_wad, t.sort_volume_24h_eth_wad AS volume_24h_eth_wad,
       COALESCE(s.holder_count, 0)::BIGINT AS holder_count, m.description, m.image_url, m.x_url, m.telegram_url, t.launch_block_hash
FROM tokens AS t
LEFT JOIN token_metadata AS m ON m.chain_id = t.chain_id AND m.token_address = t.token_address
    AND m.launch_tx_hash = t.launch_tx_hash AND m.launch_log_index = t.launch_log_index
LEFT JOIN token_stats AS s ON s.chain_id = t.chain_id AND s.token_address = t.token_address
WHERE t.chain_id = $1 AND t.phase = $2
  AND ($3::text = '' OR lower(t.name) LIKE lower($3::text) || '%' OR lower(t.symbol) LIKE lower($3::text) || '%' OR encode(t.token_address, 'hex') = lower(CASE WHEN left($3::text,2)='0x' THEN substr($3::text,3) ELSE $3::text END))
  AND ($4::numeric IS NULL OR (t.sort_volume_24h_eth_wad, t.token_address) < ($4::numeric, $5::bytea))
ORDER BY t.sort_volume_24h_eth_wad DESC, t.token_address DESC LIMIT $6::integer
`

type ListTokenCardsVolumeParams struct {
	ChainID      int64
	Phase        string
	Search       string
	AfterMetric  pgtype.Numeric
	AfterAddress []byte
	PageSize     int32
}

type ListTokenCardsVolumeRow struct {
	TokenAddress      Address
	Name              string
	Symbol            string
	Phase             string
	LaunchBlockNumber int64
	LaunchBlockTime   pgtype.Timestamptz
	TotalSupply       Uint256
	MarketCapEthWad   Uint256
	Volume24hEthWad   Uint256
	HolderCount       int64
	Description       pgtype.Text
	ImageUrl          pgtype.Text
	XUrl              pgtype.Text
	TelegramUrl       pgtype.Text
	LaunchBlockHash   Hash
}

func (q *Queries) ListTokenCardsVolume(ctx context.Context, arg ListTokenCardsVolumeParams) ([]ListTokenCardsVolumeRow, error) {
	rows, err := q.db.Query(ctx, listTokenCardsVolume,
		arg.ChainID,
		arg.Phase,
		arg.Search,
		arg.AfterMetric,
		arg.AfterAddress,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokenCardsVolumeRow{}
	for rows.Next() {
		var i ListTokenCardsVolumeRow
		if err := rows.Scan(
			&i.TokenAddress,
			&i.Name,
			&i.Symbol,
			&i.Phase,
			&i.LaunchBlockNumber,
			&i.LaunchBlockTime,
			&i.TotalSupply,
			&i.MarketCapEthWad,
			&i.Volume24hEthWad,
			&i.HolderCount,
			&i.Description,
			&i.ImageUrl,
			&i.XUrl,
			&i.TelegramUrl,
			&i.LaunchBlockHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenHolders = `-- name: ListTokenHolders :many
SELECT h.holder_address, h.balance, h.first_acquired_block_number
FROM holder_balances AS h
JOIN tokens AS t USING (chain_id, token_address)
WHERE h.chain_id = $1
  AND h.token_address = $2
  AND h.balance > 0
  AND h.holder_address <> decode(repeat('00', 20), 'hex')
  AND h.holder_address <> decode(repeat('00', 18) || 'dead', 'hex')
  AND h.holder_address <> t.curve_address
  AND h.holder_address <> t.lp_pair
  AND ($3::numeric IS NULL OR
       (h.balance, h.holder_address) < ($3::numeric, $4::bytea))
ORDER BY h.balance DESC, h.holder_address DESC
LIMIT $5::integer
`

type ListTokenHoldersParams struct {
	ChainID      int64
	TokenAddress Address
	AfterBalance pgtype.Numeric
	AfterAddress []byte
	PageSize     int32
}

type ListTokenHoldersRow struct {
	HolderAddress            Address
	Balance                  Uint256
	FirstAcquiredBlockNumber pgtype.Int8
}

func (q *Queries) ListTokenHolders(ctx context.Context, arg ListTokenHoldersParams) ([]ListTokenHoldersRow, error) {
	rows, err := q.db.Query(ctx, listTokenHolders,
		arg.ChainID,
		arg.TokenAddress,
		arg.AfterBalance,
		arg.AfterAddress,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokenHoldersRow{}
	for rows.Next() {
		var i ListTokenHoldersRow
		if err := rows.Scan(&i.HolderAddress, &i.Balance, &i.FirstAcquiredBlockNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tokenExists = `-- name: TokenExists :one
SELECT EXISTS (
    SELECT 1
    FROM tokens
    WHERE chain_id = $1
      AND token_address = $2
)
`

type TokenExistsParams struct {
	ChainID      int64
	TokenAddress Address
}

func (q *Queries) TokenExists(ctx context.Context, arg TokenExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, tokenExists, arg.ChainID, arg.TokenAddress)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
